### ISSUE TITLE
Possible to use in 18.08

### ISSUE THREAD

**Issue by jonathon-love** [refi64/zypak#1]
hi,

is there a simple trick i could do to have this build for the 18.08 flatpak runtime? or is that a bit tricky? (there are several barriers preventing us from upgrading to the 19.08 at this time).

with thanks

**Comment by refi64** [comment]
I had picked 19.08 as the target since it was sort of inevitable and it let
me use C++20 features early, though...I don't quite remember what said
features actually were. You could try compiling it on 18.08 (might have to
change -std=c++2a to -std=c++17 in the Makefile), and see what errors you
get.

**Comment by jonathon-love** [comment]
you use `string::ends_with()`

**Comment by Erick555** [comment]
@jonathon-love is there a reason for staying in 18.08? It will be out of support within few months.

**Comment by jonathon-love** [comment]
we have some dependencies that fail during compilation on 19.08, and we've not been able to make progress with them.

**Comment by Erick555** [comment]
which ones? I see [build successful here](https://github.com/flathub/org.jamovi.jamovi/pull/47).

**Comment by jonathon-love** [comment]
yeah, the situation is a bit more complicated than i've made out. it's not the application per se, it's our module library. we're not using the flatpak extensions to build our modules, because we're a cross platform application, and it's simpler to build windows, macos, and linux 'modules' using a consistent mechanism.

so we build all our modules on an appveyor instance:

https://github.com/jonathon-love/jamovi-library/

using all the flatpak platform stuff, so it's all binary compatible.

it's during the build of the modules that we get an unexpected failure:

`https://github.com/RcppCore/RcppEigen/issues/84`

and because it's on an appveyor instance, it's devilishly hard to debug.

**Comment by Erick555** [comment]
Ok, for some reason I don't see any log in https://ci.appveyor.com/project/jonathon-love/jamovi-library/build/job/ct4m2itq5hpvfs75?fullLog=true , could you upload logfile txt here or somewhere?

**Comment by jonathon-love** [comment]
it's ok, i think i've got it working! i think it turned out to be a bug in appveyor. by setting the environmental variable: `APPVEYOR_CONSOLE_DISABLE_PTY: true` the build proceeds.

with thanks

**Comment by jonathon-love** [comment]
... and sorry @refi64 for spamming you.

**Comment by refi64** [comment]
So I dropped the C++2a requirement anyway since that was apparently the only reason for it.

**Comment by jonathon-love** [comment]
the C++2a requirement never actually came up as an issue when compiling for the 18.08 (i never patched for it).

cheers

**Comment by refi64** [comment]
string_view::ends_with() was from C++20.

**Comment by jonathon-love** [comment]
oh yup, sorry, i meant the `C++2a` specified in the Makefile never came up as an issue.
