### ISSUE TITLE
Bad file descriptor error with Chrome/Edge 92 dev releases

### ISSUE THREAD

**Issue by tinywrkb** [refi64/zypak#12]
zyapk v2021.02, Edge Dev 92.0.902.2, Chrome Unstable 92.0.4515.40.

Edge and Chrome are failing to start with the following errors:

```
[28 zypak-sandbox] Failed to send spawn request to supervisor: Bad file descriptor (errno 9)
[0602/214632.645836:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (
```
Debug output for Chrome: [chrome-unstable-strace.log](https://github.com/refi64/zypak/files/6586827/chrome-unstable-strace.log)

I'm using my own Flatpak packaging for [Chrome Unstable](https://github.com/tinywrkb/flatpaks/blob/master/com.google.chrome-unstable/com.google.chrome-unstable.yaml) and [Edge Dev](https://github.com/tinywrkb/flatpaks/blob/master/com.microsoft.edge-dev/com.microsoft.edge-dev.yaml) but I'm not doing something special so I expect that the Flathub packaged Chrome stable and Edge beta apps will also break when updated to 92.

Chrome Unstable 92.0.4496.0 and Edge Dev 92.0.891.1 didn't suffer from this issue.

**Comment by tinywrkb** [comment]
CC @TheEvilSkeleton as this probably will affect com.microsoft.Edge.

**Comment by refi64** [comment]
@tinywrkb please try the latest commit and see if it works, if so I'll cut a new release soon(-ish) so we can start getting ready for 92's release.

**Comment by tinywrkb** [comment]
@refi64 thanks, it's now working perfectly with the latest Chrome Unstable and Edge Dev releases.  
Kudos for solving this so quickly.
