### ISSUE TITLE
Environment variables are eaten by zypak-helper when ELECTRON_RUN_AS_NODE=1

### ISSUE THREAD

**Issue by catsout** [refi64/zypak#19]
The problem appears when run electron with `ELECTRON_RUN_AS_NODE=1`  
It seems that it will start node cli first without using of `chrome-sandbox`, and then spawn([vscode](https://github.com/microsoft/vscode/blob/d1ae860377abbba88bd3abe1d65d88caf12a8105/src/vs/code/node/cli.ts#L370)) it self to run with chrome  

If I use `zypak-wrapper` at first with `CHROME_WRAPPER`, that spawning will be overridden to `zypak-helper exec-latest $CHROME_WRAPPER ...`  
Here `zypak-helper exec-latest` will spawn a new sandbox environment(I'm not sure, as I don't known how `SpawnLatest` works)  
As a result, the environment variables will not be inherited, which will cause some problems(linked below), as **the first run_as_node may set some environment variables used by electron**  
https://github.com/flathub/com.visualstudio.code/issues/261  
https://github.com/flathub/com.visualstudio.code/issues/259  
https://github.com/flathub/com.visualstudio.code/pull/237  

I think maybe do `execvp` without `zypak-helper exec-latest` when `ZYPAK_DISABLE_SANDBOX=1` with `CHROME_WRAPPER` to solve this problem    
Need `unset ZYPAK_DISABLE_SANDBOX` in `CHROME_WRAPPER` script or in the overridden `execvp`

**Comment by refi64** [comment]
For some context: the whole reason `SpawnLatest` needs to exist is for stuff like `chrome://restart` to work. It's expected that `chrome://restart` would re-open Chromium *to the latest version installed*, meaning we need to ask Flatpak to start the application in a new sandbox containing the latest Chromium...but when it restarts it, the environment is now cleared out.

In theory, Zypak should just be saving the original environment to more closely follow the original behavior, then this would work (I think). I'll just need to fiddle with it a bit to make sure it doesn't break anything.

**Comment by gasinvein** [comment]
From what I can tell, the only issue with vscode and zypak which can't be worked around is that `--wait` doesn't work. Is it somehow related to the fact that zypak looses environment variables?

**Comment by catsout** [comment]
> Is it somehow related to the fact that zypak looses environment variables?

https://github.com/refi64/zypak/blob/main/src/preload/host/exec_zypak_sandbox.cc#L44  
https://github.com/refi64/zypak/blob/main/src/helper/spawn_latest.cc#L25  

`execvp` is preloaded, as long as the program want to restart itself, a new spwan env will be involved, which will loss the environment variables.  

When `ELECTRON_RUN_AS_NODE=1` specified, the starting progress like:  
zypak electron --> run as node and **set some env** and unset `ELECTRON_RUN_AS_NODE` --> spwan self with zypak preload execvp --> **env lost**, run as electron --> app started  

The lost env caused that `--wait` doesn't work

**Comment by gasinvein** [comment]
Is there some particular env var responsible for `--wait`? It seems like the lock file created for wait is passed on cli.

**Comment by catsout** [comment]
I got it wrong, It's not about the environment variables on `--wait`.  
The point is that `zypak-helper host-latest|exec-latest` will not wait the process it started.  

From the [code](https://github.com/microsoft/vscode/blob/1.63.2/src/vs/code/node/cli.ts#L235 )
>// When running with --wait, we want to continue running CLI process
// until either:
// - the wait marker file has been deleted (e.g. when closing the editor)
// - the launched process terminates (e.g. due to a crash)

**Comment by gasinvein** [comment]
Seems like a distinct issue, then.

**Comment by refi64** [comment]
Please try `master` with `ZYPAK_SPAWN_LATEST_ON_REEXEC=0`.

**Comment by bytzo** [comment]
Using `ZYPAK_SPAWN_LATEST_ON_REEXEC=0` with 8424c6bcf909ca2031ebc6537d324bb64772266e seems to fix the issues in the VSCode Flatpak. Additionally, the `--wait` flag seems to function properly again.

**Comment by gasinvein** [comment]
Yep, seems to work for Code-OSS as well.
