### ISSUE TITLE
undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm

### ISSUE THREAD

**Issue by dbrgn** [refi64/zypak#20]
I'm currently packaging an Electron app with Flatpak. Running the application directly on the host works fine. If I start it with Flatpak (through zypak), the service worker crashes with the following exception:

    Unhandled exception in worker: Uncaught Error: /tmp/.org.chromium.Chromium.WfdOop: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm

Since the symbol contains some references to "isolate", I suspect it could have something to do with zypak (and not Flatpak in general). Any idea whether this could be related? Could it be an issue if a service worker loads native libraries (implemented as Node extensions)? Right now I don't really know how to debug this issue... So any help would be appreciated.

**Comment by refi64** [comment]
These definitely aren't from Zypak, but rather from Electron/Chromium itself:

```
$ c++filt _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm 
v8::V8::GlobalizeReference(v8::internal::Isolate*, unsigned long*)
```

> Could it be an issue if a service worker loads native libraries (implemented as Node extensions)

*If I had to guess*...at some point you have some library mixup involving Node, maybe a native Node extension compiled against the wrong Node version, or part of your application is trying to use one version and other parts another... This matches with [various](https://github.com/atom/github/issues/2032) [other](https://github.com/brianc/node-pg-native/issues/40) [references](https://www.reddit.com/r/Atom/comments/gw99ho/apm_throws_error/) to the exact same symbol being missing.

**Comment by dbrgn** [comment]
@refi64 thanks!
