### ISSUE TITLE
Every command are surrounded with warnings

### ISSUE THREAD

**Issue by freeseacher** [refi64/zypak#30]
Recent update to jetbrains ides leads a problem with chrome sandboxing.

but integration of zypak like this https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/534 leads to multiple warnings. 

how i can fix that warning ?

**Comment by bademux** [comment]
It is  not just warning for me  - Idea find git binary every 3-7th time. So git is totally broken

**Comment by refi64** [comment]
This is an issue with the way IDEA and PyCharm loaded Zypak, see https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/534#issuecomment-1535559093.
