### ISSUE TITLE
Some info about the printing problems and others

### ISSUE THREAD

**Issue by rany2** [refi64/zypak#4]
Almost all the other problems I was facing before with zypak were resolved after I enabled support for user namespaces in bubblewrap.

You might want to tell your Chrome flatpak users that printing, pdfs, etc. all would work when you remove bwrap's SUID and enable userns.

**Comment by analotia** [comment]
Not having `expose-pids` support doesn't just mean that you'll have performance issues, it means that chromium would break

**Comment by refi64** [comment]
Oh gosh, that shouldn't be the case at all. I'll have to do some testing
locally with the spawn strategy disabled and see what happens.

**Comment by refi64** [comment]
@rany2 would appreciate some testing to confirm that the PDF and printing issues are fixed (couldn't really test printing but PDFs should definitely work now)

**Comment by rany2** [comment]
@refi64 Better late than never but zypak does work now. Printing, PDF, etc... all work. Just saw your comment...
