### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by takluyver** [refi64/zypak#41]
It looks like there have been a few changes to Zypak in 2023, but the most recent tag is from April 2022. So unless I'm missing something, applications getting Zypak through the Electron baseapp don't get any of the recent changes.

(Something [seems to have broken](https://github.com/flathub/us.zoom.Zoom/pull/429#issuecomment-1875823339) with recent versions of Zoom inside its Flatpak, which uses Zypak. I'm not sure the 2023 changes would fix that, but it seems worth checking. :slightly_smiling_face: )

**Comment by muelli** [comment]
@refi64 do you consider tagging a release? Is anything blocking a release?

**Comment by refi64** [comment]
https://github.com/refi64/zypak/releases/tag/v2024.01.17

**Comment by takluyver** [comment]
Thanks"
